export const MODAL_CLOSE_ANIMATION_DURATION = 350
export const MODAL_OPEN_ANIMATION_DURATION = 350
export const MODAL_BACKDROP_ANIMATION_DURATION = 350
export const MODAL_DIMENSIONS = { width: 800, height: 600 }
export const WORK_MODAL_PADDING = 40
